(local Harness (require :tests.e2e.harness))
(local ButtonTest (require :tests.e2e.test-button))
(local ButtonStatesTest (require :tests.e2e.test-button-states))
(local ImageTest (require :tests.e2e.test-image))
(local HudButtonTest (require :tests.e2e.test-hud-button))
(local LauncherViewTest (require :tests.e2e.test-launcher-view))
(local SceneButtonTest (require :tests.e2e.test-scene-button))
(local SceneHudButtonTest (require :tests.e2e.test-scene-hud-button))
(local ScrollViewTest (require :tests.e2e.test-scroll-view))
(local ScrollViewTopTest (require :tests.e2e.test-scroll-view-top))
(local ListViewTest (require :tests.e2e.test-list-view))
(local ListViewExtraSpaceTest (require :tests.e2e.test-list-view-extra-space))
(local LlmMessageDialogTest (require :tests.e2e.test-llm-message-dialog))
(local LlmConversationDialogTest (require :tests.e2e.test-llm-conversation-dialog))
(local LlmChatViewTest (require :tests.e2e.test-llm-chat-view))
(local ComboBoxTest (require :tests.e2e.test-combo-box))
(local RenderCaptureTest (require :tests.e2e.test-render-capture))
(local ThemeSnapshotTest (require :tests.e2e.test-theme-snapshot))
(local GraphNodePointsTest (require :tests.e2e.test-graph-node-points))
(local HudFloatResizeTest (require :tests.e2e.test-hud-float-resize))
(local HudFloatResizeDirectTest (require :tests.e2e.test-hud-float-resize-direct))
(local XdgIconBrowserTest (require :tests.e2e.test-xdg-icon-browser))
(local StringEntityViewTest (require :tests.e2e.test-string-entity-view))
(local LinkEntityViewTest (require :tests.e2e.test-link-entity-view))
(local ListEntityViewTest (require :tests.e2e.test-list-entity-view))
(local TabViewTest (require :tests.e2e.test-tab-view))
(local SubAppTest (require :tests.e2e.test-sub-app))
(local TetrisDeepDialogTest (require :tests.e2e.test-tetris-deep-dialog))

(fn run-all []
  (ButtonTest.main)
  (ButtonStatesTest.main)
  (ImageTest.main)
  (ScrollViewTest.main)
  (ScrollViewTopTest.main)
  (ListViewTest.main)
  (ListViewExtraSpaceTest.main)
  (LlmMessageDialogTest.main)
  (LlmConversationDialogTest.main)
  (LlmChatViewTest.main)
  (ComboBoxTest.main)
  (ThemeSnapshotTest.main)
  (GraphNodePointsTest.main)
  (HudButtonTest.main)
  (LauncherViewTest.main)
  (HudFloatResizeTest.main)
  (HudFloatResizeDirectTest.main)
  (SceneButtonTest.main)
  (SceneHudButtonTest.main)
  (XdgIconBrowserTest.main)
  (StringEntityViewTest.main)
  (LinkEntityViewTest.main)
  (ListEntityViewTest.main)
  (TabViewTest.main)
  (SubAppTest.main)
  (TetrisDeepDialogTest.main)
  (RenderCaptureTest.main))

(fn main []
  (run-all)
  (print "E2E snapshots complete"))

{:main main}
