(local suite
  {:name "fast"
   :modules
   [:tests.test-pre-engine-start
    :tests.test-layout
    :tests.test-cli-args
    :tests.test-ray-box
    :tests.test-signal
    :tests.test-touch-session
    :tests.test-touch-router
    :tests.test-render-capture
    :tests.test-next-frame
    :tests.test-runtime-timers
    :tests.test-runtime-updates
    :tests.test-layout-stats-view
    :tests.test-clickables
    :tests.test-clipboard
    :tests.test-hoverables
    :tests.test-intersectables
    :tests.test-button
    :tests.test-tab-view
    :tests.test-icons
    :tests.test-combo-box
    :tests.test-font
    :tests.test-theme-widgets
    :tests.test-theme-switch
    :tests.test-text
    :tests.test-wrapped-text
    :tests.test-text-ssbo-batcher
    :tests.test-dialog
    :tests.test-hud
    :tests.test-hud-command-hints
    :tests.test-hud-control-panel
    :tests.test-hud-extended-sidebar
    :tests.test-hud-layout
    :tests.test-deep-dialog
    :tests.test-tetris-game
    :tests.test-tetris-state
    :tests.test-tetris-view
    :tests.test-graph-node-cube
    :tests.test-menu
    :tests.test-sized
    :tests.test-container
    :tests.test-flex
    :tests.test-grid
    :tests.test-padding
    :tests.test-stack
    :tests.test-next-layout
    :tests.test-next-app-widgets
    :tests.test-next-app-button
    :tests.test-next-app-core-widgets
    :tests.test-next-app-text-widget
    :tests.test-next-app-input-widget
    :tests.test-next-app-scroll-and-list
    :tests.test-next-app-interaction-router
    :tests.test-next-app-cuboid-widget
    :tests.test-next-app-quad-batcher
    :tests.test-next-app-clip-stress
    :tests.test-bucket-queue
    :tests.test-layout-root-queue
    :tests.test-scroll-area
    :tests.test-scroll-view
    :tests.test-aligned
    :tests.test-cuboid
    :tests.test-main-events
    :tests.test-states
     :tests.test-canvas-controls
      :tests.test-canvas-activity-slots
      :tests.test-activity-retention
      :tests.test-graph-activity-slots
     :tests.test-drawing-activity-slots
     :tests.test-board
    :tests.test-first-person-controls
    :tests.test-screen-pos-ray
    :tests.test-terrain-query
    :tests.test-movables
    :tests.test-resizables
    :tests.test-scene-drag
    :tests.test-list-view
    :tests.test-search-view
    :tests.test-fennel-interpreter-view
    :tests.test-launchables
    :tests.test-random
    :tests.test-tempfile
    :tests.test-graph-loaders
    :tests.test-sysinfo
    :tests.test-flamegraph
    :tests.test-units
    :tests.test-unit-manager
    :tests.test-selection
    :tests.test-callbacks
    :tests.test-logging
    :tests.test-http
    :tests.test-settings
    :tests.test-runtime-performance
    :tests.test-glm
    :tests.test-colors
    :tests.test-colorspacious
    :tests.test-toml
    :tests.test-sql-builder
    :tests.test-string-utils
    :tests.test-string-entities
    :tests.test-code-entities
    :tests.test-identity-entities
    :tests.test-link-entities
    :tests.test-list-entities
    :tests.test-notebooks
    :tests.test-link-entity-crash
    :tests.test-morphs
    :tests.test-world-nodes
    :tests.test-world-skybox-node
    :tests.test-world-background-node
    :tests.test-flat-terrain-theme
    :tests.test-perlin-terrain
    :tests.test-focus
    :tests.test-input-model
    :tests.test-dial-type
    :tests.test-input-dial-type
    :tests.test-input
    :tests.test-quit-binding
    :tests.test-input-state-binding
    :tests.test-mouse-state-binding
    :tests.test-rate-limiter
    :tests.test-realtime-offline
    :tests.test-openai-offline
    :tests.test-openai-tools-offline
    :tests.test-llm-tools
    :tests.test-agent-presets
    :tests.test-agent-presets-mcp
    :tests.test-agent-layer
    :tests.test-agent-panel
    :tests.test-agent-units
    :tests.test-disclosure-row
    :tests.test-status-badge
    :tests.test-cgltf
    :tests.test-graph-core
    :tests.test-graph-edge-batch
    :tests.test-graph-view-registry
    :tests.test-graph-view-labels
    :tests.test-vector-buffer
    :tests.test-points
    :tests.test-layered-point
    :tests.test-renderers
    :tests.test-widget-cuboid
    :tests.test-radial
    :tests.test-volume
    :tests.test-kernels
    :tests.test-physics-containment
    :tests.test-layout-physics-bodies
    :tests.test-physics
    :tests.test-polyhedron-meshes
    :tests.test-force-layout
    :tests.test-ball
    :tests.test-light-ball
    :tests.test-soccer-ball-visual
    :tests.test-car
    :tests.test-demo-car
    :tests.test-car-state
    :tests.test-heightfield-terrain
    :tests.test-graph-view
    :tests.test-graph-view-control-view
    :tests.test-hackernews-graph-view-node-views
    :tests.test-world-manager
    :tests.test-world-tabs-widget
    :tests.test-demo-browser
    :tests.test-chart
    :tests.test-repo-sha256
    :tests.test-repo-remote
    :tests.test-repo-git
    :tests.test-repo-path-policy
    :tests.test-repo-workspace
    :tests.test-repo-store
    :tests.test-repo-checks
    :tests.test-repo-presets
    :tests.test-repo-display
    :tests.test-panel-transfer]})

(local main
  (fn []
    (local runner (require :tests/runner))
    (runner.run-modules suite)))

{:name "fast"
 :modules suite.modules
 :main main}
