(local suite
  {:name "fast"
   :modules
   [:tests.test-pre-engine-start
    :tests.test-layout
    :tests.test-cli-args
    :tests.test-ray-box
    :tests.test-zmq
    :tests.test-remote-control
    :tests.test-render-capture
    :tests.test-next-frame
    :tests.test-audio-input
    :tests.test-aubio
    :tests.test-aubio-helpers
    :tests.test-aubio-pipelines
    :tests.test-aubio-stream
    :tests.test-clickables
    :tests.test-hoverables
    :tests.test-intersectables
    :tests.test-button
    :tests.test-tab-view
    :tests.test-icons
    :tests.test-combo-box
    :tests.test-theme-widgets
    :tests.test-theme-switch
    :tests.test-text
    :tests.test-dialog
    :tests.test-deep-dialog
    :tests.test-tetris-game
    :tests.test-tetris-state
    :tests.test-tetris-view
    :tests.test-menu
    :tests.test-sized
    :tests.test-container
    :tests.test-flex
    :tests.test-grid
    :tests.test-padding
    :tests.test-stack
    :tests.test-bucket-queue
    :tests.test-layout-root-queue
    :tests.test-scroll-area
    :tests.test-scroll-view
    :tests.test-aligned
    :tests.test-cuboid
    :tests.test-main-events
    :tests.test-states
    :tests.test-first-person-controls
    :tests.test-screen-pos-ray
    :tests.test-movables
    :tests.test-resizables
    :tests.test-scene-drag
    :tests.test-list-view
    :tests.test-search-view
    :tests.test-fs
    :tests.test-random
    :tests.test-fs-view
    :tests.test-tempfile
    :tests.test-external-editor
    :tests.test-process
    :tests.test-flamegraph
    :tests.test-points
    :tests.test-layered-point
    :tests.test-force-layout
    :tests.test-physics
    :tests.test-ball
    :tests.test-renderers
    :tests.test-focus
    :tests.test-input-model
    :tests.test-input
    :tests.test-quit-binding
    :tests.test-input-state-binding
    :tests.test-mouse-state-binding
    :tests.test-colors
    :tests.test-graph-view
    :tests.test-graph-core
    :tests.test-graph-view-registry
    :tests.test-graph-view-labels
    :tests.test-llm-graph
    :tests.test-llm-store
    :tests.test-llm-chat-view
    :tests.test-llm-conversation-messages-view
    :tests.test-graph-view-control-view
    :tests.test-hackernews-story-list-view
    :tests.test-hackernews-story-view
    :tests.test-hackernews-user-view
    :tests.test-hackernews-offline
    :tests.test-hackernews-graph-view-node-views
    :tests.test-chart
    :tests.test-car
    :tests.test-demo-car
    :tests.test-car-state
    :tests.test-demo-browser
    :tests.test-widget-cuboid
    :tests.test-radial
    :tests.test-glm
    :tests.test-volume
    :tests.test-settings
    :tests.test-skybox-settings
    :tests.test-flat-terrain-theme
    :tests.test-selection
    :tests.test-terminal
    :tests.test-terminal-widget
    :tests.test-terminal-renderer
    :tests.test-terminal-scrollback
    :tests.test-jobs
    :tests.test-jpeg-texture-decode
    :tests.test-callbacks
    :tests.test-logging
    :tests.test-http
    :tests.test-keyring
    :tests.test-wallet
    :tests.test-wallet-manager
    :tests.test-wallet-store
    :tests.test-wallet-view
    :tests.test-wallet-send-dialog
    :tests.test-qr-code
    :tests.test-wallet-rpc
    :tests.test-wallet-core
    :tests.test-rate-limiter
    :tests.test-openai-offline
    :tests.test-openai-tools-offline
    :tests.test-llm-tools
    :tests.test-toml
    :tests.test-cgltf
    :tests.test-string-utils
    :tests.test-xdg-icon-browser
    :tests.test-string-entities
    :tests.test-link-entities
    :tests.test-list-entities
    :tests.test-link-entity-crash
    :tests.test-graph-loaders]})

(local main
  (fn []
    (local runner (require :tests/runner))
    (runner.run-modules suite)))

{:name "fast"
 :modules suite.modules
 :main main}
