(local Sql (require :sql-builder))

(local tests [])

(fn test-basic-select-qmark []
  (local users (Sql.table "users" "u"))
  (local q0 (Sql.from users))
  (local count-cnt (Sql.as (Sql.call "COUNT" users.id) "cnt"))
  (local q1 (q0:select users.id count-cnt))
  (local q2 (q1:where (users.age:gte 18)))
  (local q3 (q2:group-by users.id))
  (local q4 (q3:having (Sql.gt (Sql.call "COUNT" users.id) 1)))
  (local q5 (q4:order-by [users.id :desc]))
  (local q6 (q5:limit 10))
  (local q (q6:offset 5))
  (local result (q:to-sql {:param-style :qmark}))
  (assert (string.find result.sql "SELECT" 1 true))
  (assert (string.find result.sql "FROM \"users\" AS \"u\"" 1 true))
  (assert (string.find result.sql "GROUP BY" 1 true))
  (assert (= (# result.params) 2))
  (assert (= (. result.params 1) 18))
  (assert (= (. result.params 2) 1)))

(fn test-named-params []
  (local users (Sql.table "users"))
  (local q0 (Sql.from users))
  (local q1 (q0:select users.id))
  (local q (q1:where (Sql.and_ (users.name:like "%sam%")
                               (users.active:eq true))))
  (local result (q:to-sql {:param-style :named}))
  (assert (string.find result.sql ":p1" 1 true))
  (assert (string.find result.sql ":p2" 1 true))
  (assert (= result.params.p1 "%sam%"))
  (assert (= result.params.p2 true)))

(fn test-ctes-and-union []
  (local users (Sql.table "users"))
  (local active0 (Sql.from users))
  (local active1 (active0:select users.id))
  (local active (active1:where (users.active:eq true)))
  (local q0 (Sql.with "active_users" active))
  (local q1 (q0:from (Sql.table "active_users")))
  (local q2 (q1:select (Sql.field nil "id")))
  (local q (q2:union (Sql.select (Sql.literal 99))))
  (local sql (q:to-sql-string))
  (assert (string.find sql "WITH \"active_users\" AS" 1 true))
  (assert (string.find sql "UNION" 1 true)))

(fn test-with-recursive-cte []
  (local users (Sql.table "users"))
  (local seed0 (Sql.from users))
  (local seed (seed0:select (Sql.literal 1)))
  (local q0 (Sql.with_recursive "nums" seed))
  (local q1 (q0:from (Sql.table "nums")))
  (local q (q1:select (Sql.field nil "id")))
  (local out (q:to-sql-string))
  (assert (string.find out "WITH RECURSIVE \"nums\" AS" 1 true)))

(fn test-insert-update-delete []
  (local users (Sql.table "users"))

  (local ins0 (Sql.insert-into users))
  (local ins1 (ins0:columns "id" "name"))
  (local ins (ins1:values [1 "sam"] [2 "pat"]))
  (local ins-sql (ins:to-sql {:param-style :qmark}))
  (assert (string.find ins-sql.sql "INSERT INTO" 1 true))
  (assert (= (# ins-sql.params) 4))

  (local upd0 (Sql.update users))
  (local upd1 (upd0:set users.name "new"))
  (local upd (upd1:where (users.id:eq 1)))
  (local upd-sql (upd:to-sql {:param-style :qmark}))
  (assert (string.find upd-sql.sql "UPDATE" 1 true))
  (assert (= (# upd-sql.params) 2))

  (local del0 (Sql.delete-from users))
  (local del (del0:where (users.id:eq 2)))
  (local del-sql (del:to-sql {:param-style :qmark}))
  (assert (string.find del-sql.sql "DELETE FROM" 1 true))
  (assert (= (# del-sql.params) 1)))

(fn test-insert-from-select []
  (local src-users (Sql.table "users"))
  (local dst-users (Sql.table "archived_users"))
  (local src0 (Sql.from src-users))
  (local src1 (src0:select src-users.id src-users.name))
  (local src (src1:where (src-users.active:eq true)))
  (local q0 (Sql.into dst-users))
  (local q1 (q0:columns "id" "name"))
  (local q2 (q1:from_select src))
  (local q3 (q2:returning dst-users.id))
  (local out (q3:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "INSERT INTO \"archived_users\" (\"id\", \"name\") SELECT" 1 true))
  (assert (string.find out.sql "RETURNING \"archived_users\".\"id\"" 1 true))
  (assert (= (# out.params) 1))
  (assert (= (. out.params 1) true))

  (local q4 (q1:values [1 "sam"]))
  (local q5 (q4:from_select src))
  (local out2 (q5:to-sql {:param-style :qmark}))
  (assert (string.find out2.sql "SELECT" 1 true))
  (assert (not (string.find out2.sql "VALUES" 1 true)))

  (local q6 (q2:values [1 "sam"]))
  (local out3 (q6:to-sql-string))
  (assert (string.find out3 "VALUES" 1 true))
  (assert (not (string.find out3 "SELECT" 1 true))))

(fn test-create-and-drop []
  (local users (Sql.table "users"))
  (local q0 (Sql.create-table users))
  (local q1 (q0:if-not-exists))
  (local q2 (q1:column "id" "INTEGER" {:primary-key? true :autoincrement? true}))
  (local q3 (q2:column "name" "TEXT" {:nullable? false}))
  (local q4 (q3:column "org_id" "INTEGER"))
  (local q5 (q4:foreign-key ["org_id"] (Sql.table "orgs") ["id"] {:on-delete "CASCADE"}))
  (local q6 (q5:strict))
  (local q (q6:without-rowid))
  (local sql (q:to-sql-string))
  (assert (string.find sql "CREATE TABLE IF NOT EXISTS" 1 true))
  (assert (string.find sql "FOREIGN KEY" 1 true))
  (assert (string.find sql "STRICT" 1 true))

  (local drop0 (Sql.drop-table users))
  (local drop1 (drop0:if-exists))
  (local drop-sql (drop1:to-sql-string))
  (assert (string.find drop-sql "DROP TABLE IF EXISTS" 1 true)))

(fn test-function-specials-and-windows []
  (local t (Sql.table "events" "e"))
  (local Fn Sql.Functions)
  (local An Sql.Analytics)

  (local cnt0 (Fn.count t.id))
  (local cnt1 (cnt0:distinct))
  (local cnt2 (cnt1:filter (t.active:eq true)))
  (local cnt3 (cnt2:over t.user_id))
  (local cnt4 (cnt3:order_by [t.created_at :desc]))
  (local cnt5 (cnt4:rows (Sql.preceding 1) Sql.CURRENT_ROW))
  (local cnt (Sql.as cnt5 "active_cnt"))
  (local cnt-alias (Sql.as (Fn.count_distinct t.id) "cnt_alias"))

  (local ranked0 (An.row_number))
  (local ranked1 (ranked0:over t.user_id))
  (local ranked2 (ranked1:orderby [t.created_at :desc]))
  (local ranked (Sql.as ranked2 "rnk"))

  (local latest0 (Fn.first_value t.kind))
  (local latest1 (latest0:ignore_nulls))
  (local latest2 (latest1:over t.user_id))
  (local latest3 (latest2:order_by [t.created_at :desc]))
  (local latest (Sql.as latest3 "latest_kind"))

  (local q0 (Sql.from t))
  (local q1 (q0:select cnt ranked latest cnt-alias
                       (Fn.current_timestamp)
                       (Fn.cast t.score "INTEGER")
                       (Fn.extract "year" t.created_at)))
  (local q (q1:where (t.score:gt 0)))
  (local out (q:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "COUNT(DISTINCT" 1 true))
  (assert (string.find out.sql "FILTER(WHERE" 1 true))
  (assert (string.find out.sql "OVER(" 1 true))
  (assert (string.find out.sql "IGNORE NULLS" 1 true))
  (assert (string.find out.sql "ROWS BETWEEN 1 PRECEDING AND CURRENT ROW" 1 true))
  (assert (string.find out.sql "CURRENT_TIMESTAMP" 1 true))
  (assert (not (string.find out.sql "CURRENT_TIMESTAMP(" 1 true)))
  (assert (string.find out.sql "CAST(" 1 true))
  (assert (string.find out.sql "EXTRACT(" 1 true)))

(fn test-joins-set-op-aliases-and-ddl-builders []
  (local users (Sql.table "users" "u"))
  (local teams (Sql.table "teams" "t"))

  (local q0 (Sql.from users))
  (local q1 (q0:select users.id teams.id))
  (local j1 (q1:left_outer_join teams))
  (local q2 (j1:on (users.team_id:eq teams.id)))
  (local q3 (q2:join-using (Sql.table "user_tags" "ut") ["user_id"] :inner))
  (local sql-join (q3:to-sql-string))
  (assert (string.find sql-join "LEFT OUTER JOIN" 1 true))
  (assert (string.find sql-join "USING (\"user_id\")" 1 true))

  (local j2 (q1:join (Sql.table "teams2" "t2")))
  (local q4 (j2:cross))
  (local sql-join2 (q4:to-sql-string))
  (assert (string.find sql-join2 "CROSS JOIN" 1 true))

  (local s10 (Sql.select (Sql.literal 1)))
  (local s1 (s10:from users))
  (local s20 (Sql.select (Sql.literal 2)))
  (local s2 (s20:from users))
  (local set1 (s1:except-of s2))
  (local set-sql1 (set1:to-sql-string))
  (local set2 (s1:minus s2))
  (local set-sql2 (set2:to-sql-string))
  (assert (string.find set-sql1 "EXCEPT" 1 true))
  (assert (string.find set-sql2 "EXCEPT" 1 true))

  (local idx-users (Sql.table "users"))
  (local idx0 (Sql.create-index "idx_users_name"))
  (local idx1 (idx0:if-not-exists))
  (local idx2 (idx1:unique))
  (local idx3 (idx2:on idx-users idx-users.name))
  (local idx4 (idx3:where (idx-users.active:eq true)))
  (local idx-sql (idx4:to-sql {:param-style :qmark}))
  (assert (string.find idx-sql.sql "CREATE UNIQUE INDEX IF NOT EXISTS \"idx_users_name\"" 1 true))
  (assert (string.find idx-sql.sql " ON \"users\" " 1 true))
  (assert (string.find idx-sql.sql " WHERE " 1 true))
  (assert (= (# idx-sql.params) 1))

  (local vq0 (Sql.from users))
  (local vq (vq0:select users.id users.name))
  (local view0 (Sql.create-view "active_users"))
  (local view1 (view0:if-not-exists))
  (local view2 (view1:temporary))
  (local view3 (view2:as vq))
  (local view-sql (view3:to-sql-string))
  (assert (string.find view-sql "CREATE TEMP VIEW IF NOT EXISTS \"active_users\" AS SELECT" 1 true)))

(fn test-explicit-parameter-placeholders []
  (local users (Sql.table "users"))
  (local q0 (Sql.from users))
  (local q1
    (q0:select users.id
               (Sql.parameter "$custom")
               (Sql.qmark-parameter)
               (Sql.numeric-parameter 3)
               (Sql.named-parameter "user_name")
               (Sql.format-parameter)
               (Sql.pyformat-parameter "id")))
  (local q2
    (q1:where (Sql.and_ (Sql.eq users.id (Sql.qmark-parameter))
                        (Sql.eq users.name (Sql.named-parameter "name")))))
  (local out (q2:to-sql-string))
  (assert (string.find out "$custom" 1 true))
  (assert (string.find out "?" 1 true))
  (assert (string.find out ":3" 1 true))
  (assert (string.find out ":user_name" 1 true))
  (assert (string.find out "%s" 1 true))
  (assert (string.find out "%(id)s" 1 true))
  (assert (string.find out ":name" 1 true)))

(fn test-insert-replace-and-ignore []
  (local users (Sql.table "users"))
  (local q0 (Sql.insert-into users))
  (local q1 (q0:columns "id" "name"))
  (local q2 (q1:ignore))
  (local q3 (q2:values [1 "a"]))
  (local out-ignore (q3:to-sql-string))
  (assert (string.find out-ignore "INSERT OR IGNORE INTO" 1 true))

  (local q4 (q1:replace [2 "b"]))
  (local out-replace (q4:to-sql-string))
  (assert (string.find out-replace "INSERT OR REPLACE INTO" 1 true)))

(fn test-table-convenience-methods []
  (local users (Sql.table "users"))
  (local ua (users:as "u"))
  (local q1 (ua:select ua.id))
  (local out1 (q1:to-sql-string))
  (assert (string.find out1 "FROM \"users\" AS \"u\"" 1 true))

  (local q2 (ua:update))
  (local q3 (q2:set ua.name "x"))
  (local out2 (q3:to-sql {:param-style :qmark}))
  (assert (string.find out2.sql "UPDATE \"users\" AS \"u\"" 1 true))
  (assert (= (# out2.params) 1))

  (local q4 (ua:insert [1 "alice"]))
  (local out3 (q4:to-sql {:param-style :qmark}))
  (assert (string.find out3.sql "INSERT INTO \"users\" AS \"u\"" 1 true))
  (assert (= (# out3.params) 2)))

(fn test-for-update-and-schema-database-helpers []
  (local db (Sql.Database "hospital"))
  (local schema db.public)
  (local patients schema.patients)
  (local q0 (Sql.from patients))
  (local q1 (q0:select patients.id))
  (local sql (q1:to-sql-string))
  (assert (string.find sql "FROM \"hospital\".\"public\".\"patients\"" 1 true))
  (local (ok-fu _) (pcall (fn [] (q1:for-update))))
  (assert (not ok-fu))

  (local tables (Sql.Tables ["users" "u"] "teams"))
  (assert (= (# tables) 2))
  (assert (= (. (. tables 1) :_alias) "u"))
  (local columns (Sql.Columns ["id" "INTEGER"] "name"))
  (assert (= (# columns) 2))
  (assert (= (. (. columns 1) :type) "INTEGER")))

(fn test-parity-method-surface []
  (local t (Sql.table "events"))
  (local q0 (Sql.from t))
  (local q1 (q0:select t.id t.kind))
  (local q2 (q1:slice 10 15))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "LIMIT 5" 1 true))
  (assert (string.find out.sql "OFFSET 10" 1 true))

  (local (ok-prewhere _) (pcall (fn [] (q1:prewhere (t.kind:eq "audit")))))
  (local (ok-use _) (pcall (fn [] (q1:use-index "idx_kind"))))
  (local (ok-force _) (pcall (fn [] (q1:force-index "idx_kind"))))
  (local (ok-totals _) (pcall (fn [] (q1:with-totals))))
  (local (ok-rollup _) (pcall (fn [] (q1:rollup t.kind))))
  (local (ok-hash-join _) (pcall (fn [] (q1:hash_join (Sql.table "x") (t.id:eq 1)))))
  (assert (not ok-prewhere))
  (assert (not ok-use))
  (assert (not ok-force))
  (assert (not ok-totals))
  (assert (not ok-rollup))
  (assert (not ok-hash-join))

  (local ct0 (Sql.create-table "v_events"))
  (local (ok-unlogged _) (pcall (fn [] (ct0:unlogged))))
  (local (ok-sysver _) (pcall (fn [] (ct0:with_system_versioning))))
  (local (ok-period _) (pcall (fn [] (ct0:period_for "validity" "valid_from" "valid_to"))))
  (assert (not ok-unlogged))
  (assert (not ok-sysver))
  (assert (not ok-period))

  (local (ok-table-for _) (pcall (fn [] (t:for_ (t.id:eq 1)))))
  (local (ok-table-portion _) (pcall (fn [] (t:for_portion "p"))))
  (assert (not ok-table-for))
  (assert (not ok-table-portion))

  (local ct0 (Sql.create-table "archived_events"))
  (local ct1 (ct0:if-not-exists))
  (local ct2 (ct1:columns ["id" "INTEGER"] ["kind" "TEXT"]))
  (local ct-sql (ct2:to-sql-string))
  (assert (string.find ct-sql "CREATE TABLE IF NOT EXISTS \"archived_events\"" 1 true))
  (assert (string.find ct-sql "\"id\" INTEGER" 1 true))

  (local src0 (Sql.from t))
  (local src (src0:select t.id t.kind))
  (local ct-as0 (Sql.create-table "archived_events_copy"))
  (local ct-as1 (ct-as0:if-not-exists))
  (local ct-as2 (ct-as1:as-select src))
  (local ct-as-sql (ct-as2:to-sql-string))
  (assert (string.find ct-as-sql "CREATE TABLE IF NOT EXISTS \"archived_events_copy\" AS SELECT" 1 true)))

(fn test-query-facade-and-underscore-aliases []
  (local Query Sql.Query)
  (local users (Query.Table "users"))
  (local q0 (Query.from_ users))
  (local q1 (q0:select users.id))
  (local (ok-fu _) (pcall (fn [] (q1:for_update))))
  (assert (not ok-fu))
  (local q2 (q1:union_all (Query.select (Sql.literal 1))))
  (local q3 (q2:except_of (Query.select (Sql.literal 2))))
  (local sql (q3:to-sql-string))
  (assert (string.find sql "UNION ALL" 1 true))
  (assert (string.find sql "EXCEPT" 1 true))

  (local i0 (Query.into users))
  (local i1 (i0:columns "id" "name"))
  (local i2 (i1:values [1 "sam"]))
  (local ins (i2:to-sql {:param-style :qmark}))
  (assert (string.find ins.sql "INSERT INTO" 1 true))
  (assert (= (# ins.params) 2))

  (local src0 (Query.select users.id))
  (local wq (Query.with_ src0 "source_users"))
  (local wq2 (wq:from (Sql.table "source_users")))
  (local wq3 (wq2:select (Sql.field nil "id")))
  (local wsql (wq3:to-sql-string))
  (assert (string.find wsql "WITH \"source_users\" AS" 1 true))

  (local (ok-drop-db _) (pcall (fn [] (Query.drop_database "x"))))
  (local (ok-drop-user _) (pcall (fn [] (Query.drop_user "u"))))
  (assert (not ok-drop-db))
  (assert (not ok-drop-user)))

(fn test-insert-on-conflict-and-returning []
  (local users (Sql.table "users"))
  (local q0 (Sql.into users))
  (local q1 (q0:columns "id" "name" "updated_at"))
  (local q2 (q1:values [1 "sam" "2026-01-01"]))
  (local q3 (q2:on-conflict "id"))
  (local q4 (q3:do-update))
  (local q5 (q4:set "name" (Sql.excluded "name")))
  (local q6 (q5:set "updated_at" (Sql.excluded "updated_at")))
  (local q7 (q6:conflict-where (users.active:eq true)))
  (local q8 (q7:returning users.id users.name))
  (local out (q8:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "ON CONFLICT(\"id\") DO UPDATE SET" 1 true))
  (assert (string.find out.sql "excluded.\"name\"" 1 true))
  (assert (string.find out.sql "WHERE (" 1 true))
  (assert (string.find out.sql "RETURNING \"users\".\"id\", \"users\".\"name\"" 1 true))
  (assert (= (# out.params) 4)))

(fn test-insert-on-conflict-do-nothing-and-replace-alias []
  (local users (Sql.table "users"))

  (local q0 (Sql.into users))
  (local q1 (q0:columns "id" "name"))
  (local q2 (q1:values [1 "sam"]))
  (local q3 (q2:on_conflict "id"))
  (local q4 (q3:do_nothing))
  (local out1 (q4:to-sql-string))
  (assert (string.find out1 "ON CONFLICT(\"id\") DO NOTHING" 1 true))

  (local q5 (q1:insert_or_replace [2 "pat"]))
  (local out2 (q5:to-sql-string))
  (assert (string.find out2 "INSERT OR REPLACE INTO" 1 true)))

(fn test-dml-returning-and-delete-builder []
  (local users (Sql.table "users"))

  (local u0 (Sql.update users))
  (local u1 (u0:set users.name "new"))
  (local u2 (u1:where (users.id:eq 1)))
  (local u3 (u2:returning users.id users.name))
  (local usql (u3:to-sql-string))
  (assert (string.find usql "UPDATE" 1 true))
  (assert (string.find usql "RETURNING" 1 true))

  (local d0 (users:delete))
  (local d1 (d0:where (users.id:eq 7)))
  (local d2 (d1:returning users.id))
  (local dsql (d2:to-sql-string))
  (assert (string.find dsql "DELETE FROM" 1 true))
  (assert (string.find dsql "RETURNING \"users\".\"id\"" 1 true)))

(fn test-term-aliases-isin-notin-and-null-checks []
  (local users (Sql.table "users"))
  (local q0 (Sql.from users))
  (local q1 (q0:select users.id))
  (local q2
    (q1:where (Sql.and_ (users.id:isin [1 2 3])
                        (users.role:contains ["doctor" "nurse"])
                        (users.state:notin ["archived" "deleted"])
                        (users.kind:not_contains ["temp"])
                        (users.deleted_at:isnull)
                        (users.created_at:isnotnull))))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql " IN (" 1 true))
  (assert (string.find out.sql " NOT IN (" 1 true))
  (assert (string.find out.sql " IS NULL" 1 true))
  (assert (string.find out.sql " IS NOT NULL" 1 true))
  (assert (= (# out.params) 8)))

(fn test-pattern-operator-family []
  (local t (Sql.table "events"))
  (local q0 (Sql.from t))
  (local q1 (q0:select t.id))
  (local q2
    (q1:where (Sql.and_ (t.kind:glob "audit*")
                        (t.kind:regexp "^[a-z]+$"))))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql " GLOB " 1 true))
  (assert (string.find out.sql " REGEXP " 1 true))
  (assert (= (# out.params) 2))

  (local (ok-ilike _) (pcall (fn [] ((q1:where (t.kind:ilike "%audit%")):to-sql-string))))
  (local (ok-not-ilike _) (pcall (fn [] ((q1:where (t.kind:not-ilike "%debug%")):to-sql-string))))
  (local (ok-rlike _) (pcall (fn [] ((q1:where (t.kind:rlike "audit|event")):to-sql-string))))
  (local (ok-regex _) (pcall (fn [] ((q1:where (t.kind:regex "audit")):to-sql-string))))
  (assert (not ok-ilike))
  (assert (not ok-not-ilike))
  (assert (not ok-rlike))
  (assert (not ok-regex)))

(fn test-case-builder-searched-and-simple []
  (local t (Sql.table "events"))

  (local status0 (Sql.case))
  (local status1 (status0:when (t.score:gte 90) "A"))
  (local status2 (status1:when (t.score:gte 80) "B"))
  (local status3 (status2:else_ "C"))
  (local status (status3:as "grade"))

  (local kind0 (Sql.case t.kind))
  (local kind1 (kind0:when "audit" "A"))
  (local kind2 (kind1:when "debug" "D"))
  (local kind (kind2:else_ "?"))

  (local q0 (Sql.from t))
  (local q1 (q0:select status kind))
  (local out (q1:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "CASE WHEN" 1 true))
  (assert (string.find out.sql "THEN" 1 true))
  (assert (string.find out.sql "ELSE" 1 true))
  (assert (string.find out.sql "CASE \"events\".\"kind\" WHEN" 1 true))
  (assert (string.find out.sql "AS \"grade\"" 1 true))
  (assert (= (# out.params) 10)))

(fn test-tuple-and-composite-in []
  (local t (Sql.table "events"))
  (local key (Sql.tuple t.user_id t.kind))
  (local q0 (Sql.from t))
  (local q1 (q0:select key))
  (local q2
    (q1:where (Sql.in_ key [(Sql.Tuple 1 "audit")
                            (Sql.Tuple 2 "debug")])))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "(\"events\".\"user_id\", \"events\".\"kind\")" 1 true))
  (assert (string.find out.sql " IN ((?, ?), (?, ?))" 1 true))
  (assert (= (# out.params) 4))
  (assert (= (. out.params 1) 1))
  (assert (= (. out.params 2) "audit"))
  (assert (= (. out.params 3) 2))
  (assert (= (. out.params 4) "debug")))

(fn test-temporal-and-all-helpers-are-strict-errors []
  (local t (Sql.table "events"))
  (local q0 (Sql.from t))
  (local q1 (q0:select t.id))

  (local (ok-from-to _)
    (pcall (fn []
             ((q1:where (t.created_at:from-to "2026-01-01" "2026-12-31")):to-sql-string))))
  (local (ok-as-of _)
    (pcall (fn []
             ((q1:where (t.created_at:as-of "2026-01-01")):to-sql-string))))
  (local (ok-all _)
    (pcall (fn []
             (Sql.to-sql-string (Sql.eq t.id (Sql.all_ (Sql.select (Sql.literal 1))))))))
  (local (ok-any _)
    (pcall (fn []
             (Sql.to-sql-string (Sql.eq t.id (Sql.any_ (Sql.select (Sql.literal 1))))))))
  (assert (not ok-from-to))
  (assert (not ok-as-of))
  (assert (not ok-all))
  (assert (not ok-any)))

(fn test-bitwise-and-shift-operators []
  (local t (Sql.table "events"))
  (local q0 (Sql.from t))
  (local q1
    (q0:select (Sql.bitwiseand t.flags 4)
               (Sql.lshift t.level 1)
               (Sql.rshift t.level 1)))
  (local q2
    (q1:where (Sql.eq (t.flags:bitwiseand 2) 2)))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql " & " 1 true))
  (assert (string.find out.sql " << " 1 true))
  (assert (string.find out.sql " >> " 1 true))
  (assert (= (# out.params) 5)))

(fn test-unary-negate-and-neg []
  (local t (Sql.table "events"))
  (local q0 (Sql.from t))
  (local q1
    (q0:select (Sql.neg t.score)))
  (local q2
    (q1:where (t.active:negate)))
  (local q3
    (q2:where (Sql.negate (Sql.eq t.kind "debug"))))
  (local out (q3:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "(-\"events\".\"score\")" 1 true))
  (assert (string.find out.sql "(NOT \"events\".\"active\")" 1 true))
  (assert (string.find out.sql "(NOT (\"events\".\"kind\" = ?))" 1 true))
  (assert (= (# out.params) 1))
  (assert (= (. out.params 1) "debug")))

(fn test-term-slice-between-sugar []
  (local users (Sql.table "users"))
  (local q0 (Sql.from users))
  (local q1 (q0:select users.id))
  (local q2
    (q1:where (Sql.and_ (users.age:slice 18 65)
                        (Sql.slice users.score 10 20))))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql " BETWEEN " 1 true))
  (assert (= (# out.params) 4))
  (assert (= (. out.params 1) 18))
  (assert (= (. out.params 2) 65))
  (assert (= (. out.params 3) 10))
  (assert (= (. out.params 4) 20)))

(fn test-field-and-table-alias-surface []
  (local users (Sql.table "users"))
  (local id1 users.id)
  (local id2 (users:field "id"))
  (local all-cols (users:star))
  (local q0 (Sql.from users))
  (local q1 (q0:select id1 id2 all-cols))
  (local q2
    (q1:where (Sql.and_ (users.name:not_like "%tmp%")
                        (users.deleted_at:is_null)
                        (users.created_at:is_not_null))))
  (local out (q2:to-sql {:param-style :qmark}))
  (assert (string.find out.sql "\"users\".\"id\", \"users\".\"id\", \"users\".*" 1 true))
  (assert (string.find out.sql "NOT LIKE" 1 true))
  (assert (string.find out.sql "IS NULL" 1 true))
  (assert (string.find out.sql "IS NOT NULL" 1 true))
  (assert (= (# out.params) 1))
  (assert (= (. out.params 1) "%tmp%")))

(table.insert tests {:name "sql builder basic select" :fn test-basic-select-qmark})
(table.insert tests {:name "sql builder named params" :fn test-named-params})
(table.insert tests {:name "sql builder cte and union" :fn test-ctes-and-union})
(table.insert tests {:name "sql builder with recursive cte" :fn test-with-recursive-cte})
(table.insert tests {:name "sql builder insert update delete" :fn test-insert-update-delete})
(table.insert tests {:name "sql builder insert from select" :fn test-insert-from-select})
(table.insert tests {:name "sql builder create and drop" :fn test-create-and-drop})
(table.insert tests {:name "sql builder function specials and windows" :fn test-function-specials-and-windows})
(table.insert tests {:name "sql builder joins set aliases and ddl builders" :fn test-joins-set-op-aliases-and-ddl-builders})
(table.insert tests {:name "sql builder explicit parameter placeholders" :fn test-explicit-parameter-placeholders})
(table.insert tests {:name "sql builder insert replace and ignore" :fn test-insert-replace-and-ignore})
(table.insert tests {:name "sql builder table convenience methods" :fn test-table-convenience-methods})
(table.insert tests {:name "sql builder for-update and schema/database helpers" :fn test-for-update-and-schema-database-helpers})
(table.insert tests {:name "sql builder parity method surface" :fn test-parity-method-surface})
(table.insert tests {:name "sql builder query facade and underscore aliases" :fn test-query-facade-and-underscore-aliases})
(table.insert tests {:name "sql builder insert on conflict and returning" :fn test-insert-on-conflict-and-returning})
(table.insert tests {:name "sql builder insert on conflict do nothing and replace alias" :fn test-insert-on-conflict-do-nothing-and-replace-alias})
(table.insert tests {:name "sql builder dml returning and delete builder" :fn test-dml-returning-and-delete-builder})
(table.insert tests {:name "sql builder term aliases isin notin and null checks" :fn test-term-aliases-isin-notin-and-null-checks})
(table.insert tests {:name "sql builder pattern operator family" :fn test-pattern-operator-family})
(table.insert tests {:name "sql builder case builder searched and simple" :fn test-case-builder-searched-and-simple})
(table.insert tests {:name "sql builder tuple and composite in" :fn test-tuple-and-composite-in})
(table.insert tests {:name "sql builder temporal and all helpers are strict errors" :fn test-temporal-and-all-helpers-are-strict-errors})
(table.insert tests {:name "sql builder bitwise and shift operators" :fn test-bitwise-and-shift-operators})
(table.insert tests {:name "sql builder unary negate and neg" :fn test-unary-negate-and-neg})
(table.insert tests {:name "sql builder term slice between sugar" :fn test-term-slice-between-sugar})
(table.insert tests {:name "sql builder field and table alias surface" :fn test-field-and-table-alias-surface})

{:name "test-sql-builder"
 :tests tests
 :main (fn []
         (each [_ test (ipairs tests)]
           (local (ok err) (pcall (. test :fn)))
           (if (not ok)
               (error (.. test.name ": " (tostring err))))))}
