(local glm (require :glm))
(local CarState (require :car-state))
(local DemoCar (require :demo-car))
(local BuildContext (require :build-context))
(local {: LayoutRoot} (require :layout))
(local States (require :states))

(local tests [])

(local bt (require :bt))
(fn ensure-events-and-states []
  (when (not (and app.engine app.engine.events app.engine.events.updated))
    (reset-engine-events))
  (when (not (and app.engine app.states))
    (set app.states (States))))

(fn build-demo-car [position]
  (local ctx (BuildContext {:clickables (assert app.clickables "test requires app.clickables")
                            :hoverables (assert app.hoverables "test requires app.hoverables")}))
  (local builder (DemoCar {:position position}))
  (local host (builder ctx))
  (host.layout:measurer)
  (set host.layout.size host.layout.measure)
  (host.layout:layouter)
  (local root (LayoutRoot {:log-dirt? false}))
  (host.layout:set-root root)
  (root:update)
  (set app.scene {:entity host})
  {:host host :root root})

(fn vehicle-binding-creates-raycast []
  (assert bt "Vehicle test requires Bullet bindings")
  (assert (and app.engine app.engine.physics) "Physics instance not available")
  (app.engine.physics:setGravity 0 -9.8 0)
  (local shape (bt.BoxShape (bt.Vector3 1 0.5 2)))
  (local transform (bt.Transform))
  (transform:setIdentity)
  (transform:setOrigin (bt.Vector3 0 2 0))
  (local motion (bt.DefaultMotionState transform))
  (local inertia (bt.Vector3 0 0 0))
  (shape:calculateLocalInertia 800 inertia)
  (local info (bt.RigidBodyConstructionInfo 800 motion shape inertia))
  (local body (bt.RigidBody info))
  (local raycaster (bt.DefaultVehicleRaycaster (app.engine.physics:getWorld)))
  (local tuning (bt.VehicleTuning))
  (local vehicle (bt.RaycastVehicle tuning body raycaster))
  (vehicle:setCoordinateSystem 2 1 0)
  (local wheel-dir (bt.Vector3 0 -1 0))
  (local wheel-axle (bt.Vector3 0 0 1))
  (vehicle:addWheel (bt.Vector3 -0.6 0.6 -0.8) wheel-dir wheel-axle 0.3 0.4 tuning true)
  (vehicle:addWheel (bt.Vector3 -0.6 0.6 0.8) wheel-dir wheel-axle 0.3 0.4 tuning true)
  (vehicle:addWheel (bt.Vector3 0.6 0.6 -0.8) wheel-dir wheel-axle 0.3 0.4 tuning false)
  (vehicle:addWheel (bt.Vector3 0.6 0.6 0.8) wheel-dir wheel-axle 0.3 0.4 tuning false)
  (app.engine.physics:addRigidBody body)
  (local wheel-count (vehicle:getNumWheels))
  (local chassis-transform (vehicle:getChassisWorldTransform))
  (local origin (chassis-transform:getOrigin))
  (app.engine.physics:removeRigidBody body)
  (assert (= wheel-count 4) (.. "Expected 4 wheels, got " wheel-count))
  (assert origin "Vehicle origin missing after setup")
  (assert (> origin.y 0.5) (.. "Vehicle chassis y unexpectedly low: " origin.y)))

(fn car-state-drives-forward []
  (assert bt "Car state test requires Bullet bindings")
  (assert (and app.engine app.engine.physics) "Physics instance not available")
  (ensure-events-and-states)
  (local build (build-demo-car (glm.vec3 0 0 0)))
  (local host build.host)
  (local state (CarState))
  (state:on-enter)
  (state:on-key-down {:key CarState.KEY.forward})
  (state:on-key-down {:key CarState.KEY.left})
  (state:on-updated 0.016)
  (local internal state.__car_state)
  (local vehicle (and internal internal.vehicle))
  (local steer (and internal internal.steer))
  (state:on-key-up {:key CarState.KEY.forward})
  (state:on-key-up {:key CarState.KEY.left})
  (state:on-leave)
  (host:drop)
  (assert vehicle "Car state did not create a vehicle")
  (assert (= (vehicle:getNumWheels) 4) "Vehicle did not add four wheels")
  (assert (< (or steer 0) 0) "Left key did not update steering state"))

(fn car-state-ignores-first-person-controls []
  (ensure-events-and-states)
  (local build (build-demo-car (glm.vec3 0 0 0)))
  (local host build.host)
  (var called 0)
  (set app.first-person-controls {:update (fn [_ delta]
                                              (set called (+ called 1))
                                              (assert delta "Expected delta to be provided"))})
  (local state (CarState))
  (state:on-enter)
  (state:on-updated 0.02)
  (state:on-leave)
  (host:drop)
  (assert (= called 0) "Car state should not forward updates to first-person controls"))

(fn car-state-survives-gc-during-physics-step []
  (assert bt "Car state test requires Bullet bindings")
  (assert (and app.engine app.engine.physics) "Physics instance not available")
  (ensure-events-and-states)
  (local build (build-demo-car (glm.vec3 0 0 0)))
  (local host build.host)
  (local state (CarState))
  (state:on-enter)
  (local internal state.__car_state)
  (assert internal.vehicle "Car state did not create a vehicle")
  (collectgarbage)
  (collectgarbage)
  (app.engine.physics:update 16)
  (state:on-updated 0.016)
  (assert internal.vehicle "Vehicle lost during physics update")
  (state:on-leave)
  (host:drop))

(table.insert tests {:name "Vehicle bindings expose raycast vehicle" :fn vehicle-binding-creates-raycast})
(table.insert tests {:name "Car state moves car with keyboard input" :fn car-state-drives-forward})
(table.insert tests {:name "Car state does not touch first-person controls" :fn car-state-ignores-first-person-controls})
(table.insert tests {:name "Car state keeps Bullet objects alive across GC" :fn car-state-survives-gc-during-physics-step})

(local main
  (fn []
    (local runner (require :tests/runner))
    (runner.run-tests {:name "car-state"
                       :tests tests})))

{:name "car-state"
 :tests tests
 :main main}
