(local _ (require :main))
(local Padding (require :padding))
(local Text (require :text))
(local BuildContext (require :build-context))
(local logging (require :logging))
(local ctx (BuildContext {}))
(local padding ((Padding {:child (Text {:text "hi"})}) ctx))
(logging.debug padding)
(logging.debug padding.child)
