(local Signal (require :signal))


{:updated (Signal)
 :gamepad-added (Signal)
 :gamepad-removed (Signal)
 :gamepad-axis-motion (Signal)
 :gamepad-button-up (Signal)
 :gamepad-button-down (Signal)
 :text-input (Signal)
 :text-editing (Signal)
 :mouse-wheel (Signal)
 :mouse-button-up (Signal)
 :mouse-button-down (Signal)
 :mouse-motion (Signal)
 :key-up (Signal)
 :key-down (Signal)
 :window-resized (Signal)
 :window-pixel-size-changed (Signal)
 :window-mode-changed (Signal)
 :window-focus-changed (Signal)
 :window-minimized-changed (Signal)
 :window-occluded-changed (Signal)
 :window-hidden-changed (Signal)
 :app-suspended-changed (Signal)
 :screen-locked-changed (Signal)
 :on-battery-changed (Signal)
 :video-playback-active-changed (Signal)}
