(fn install [opts]
  (local exports {})
  (set exports.table opts.table*)
  (set exports.Table opts.table*)
  (set exports.Tables (fn [...] (opts.make-tables [...] {})))
  (set exports.Columns (fn [...] (opts.make-columns [...])) )
  (set exports.field opts.field*)
  (set exports.star opts.star)
  (set exports.Schema opts.schema*)
  (set exports.Database opts.database*)
  (set exports.raw opts.raw)
  (set exports.literal opts.literal)
  (set exports.param opts.param)
  (set exports.parameter opts.parameter)
  (set (. exports :qmark-parameter) (fn [] {:__tag :placeholder :kind :qmark}))
  (set (. exports :numeric-parameter) (fn [placeholder] {:__tag :placeholder :kind :numeric :placeholder placeholder}))
  (set (. exports :named-parameter) (fn [placeholder] {:__tag :placeholder :kind :named :placeholder placeholder}))
  (set (. exports :format-parameter) (fn [] {:__tag :placeholder :kind :format}))
  (set (. exports :pyformat-parameter) (fn [placeholder] {:__tag :placeholder :kind :pyformat :placeholder placeholder}))

  (set exports.select opts.select)
  (set exports.from opts.from)
  (set exports.from_ opts.from)
  (set exports.with opts.with)
  (set exports.with_ (fn [subquery name] (opts.with name subquery)))
  (set (. exports :with-recursive) opts.with-recursive)
  (set exports.with_recursive opts.with-recursive)
  (set (. exports :insert-into) opts.insert-into)
  (set exports.into opts.into)
  (set exports.insert_into opts.insert-into)
  (set exports.update opts.update)
  (set (. exports :delete-from) opts.delete-from)
  (set exports.delete_from opts.delete-from)
  (set (. exports :create-table) opts.create-table)
  (set exports.create_table opts.create-table)
  (set (. exports :create-index) (fn [name] (opts.create-create-index-query name)))
  (set exports.create_index (fn [name] (opts.create-create-index-query name)))
  (set (. exports :create-view) (fn [name] (opts.create-create-view-query name)))
  (set exports.create_view (fn [name] (opts.create-create-view-query name)))
  (set (. exports :drop-table) opts.drop-table)
  (set exports.drop_table opts.drop-table)
  (set (. exports :drop-database) (fn [target] (error "drop-database is not supported in sqlite sql-builder")))
  (set exports.drop_database (. exports :drop-database))
  (set (. exports :drop-user) (fn [user] (error "drop-user is not supported in sqlite sql-builder")))
  (set exports.drop_user (. exports :drop-user))
  (set (. exports :drop-view) opts.drop-view)
  (set exports.drop_view opts.drop-view)
  (set (. exports :drop-index) opts.drop-index)
  (set exports.drop_index opts.drop-index)

  (set exports.as opts.as)
  (set exports.eq (fn [left right] ((. opts :binary) :eq left right)))
  (set exports.ne (fn [left right] ((. opts :binary) :ne left right)))
  (set exports.gt (fn [left right] ((. opts :binary) :gt left right)))
  (set exports.gte (fn [left right] ((. opts :binary) :gte left right)))
  (set exports.lt (fn [left right] ((. opts :binary) :lt left right)))
  (set exports.lte (fn [left right] ((. opts :binary) :lte left right)))
  (set exports.like (fn [left right] ((. opts :binary) :like left right)))
  (set (. exports :not-like) (fn [left right] ((. opts :binary) :not_like left right)))
  (set exports.not_like (. exports :not-like))
  (set exports.glob (fn [left right] ((. opts :binary) :glob left right)))
  (set exports.ilike (fn [left right] ((. opts :binary) :ilike left right)))
  (set (. exports :not-ilike) (fn [left right] ((. opts :binary) :not_ilike left right)))
  (set exports.not_ilike (. exports :not-ilike))
  (set exports.regex (fn [left right] ((. opts :binary) :regex left right)))
  (set exports.regexp (fn [left right] ((. opts :binary) :regexp left right)))
  (set exports.rlike (fn [left right] ((. opts :binary) :rlike left right)))
  (set exports.bitwiseand (fn [left right] ((. opts :binary) :bitand left right)))
  (set exports.lshift (fn [left right] ((. opts :binary) :lshift left right)))
  (set exports.rshift (fn [left right] ((. opts :binary) :rshift left right)))
  (set exports.in_
    (fn [left items]
      (if (and (= (type items) :table) (not (. items :__tag)))
          {:__tag :in :left ((. opts :wrap-expr) left) :values (icollect [_ v (ipairs items)] ((. opts :wrap-expr) v))}
          {:__tag :in :left ((. opts :wrap-expr) left) :values ((. opts :wrap-expr) items)})))
  (set exports.contains (fn [left items] (exports.in_ left items)))
  (set (. exports :not-in)
    (fn [left items]
      (if (and (= (type items) :table) (not (. items :__tag)))
          {:__tag :not-in :left ((. opts :wrap-expr) left) :values (icollect [_ v (ipairs items)] ((. opts :wrap-expr) v))}
          {:__tag :not-in :left ((. opts :wrap-expr) left) :values ((. opts :wrap-expr) items)})))
  (set exports.not_in (. exports :not-in))
  (set exports.notin (. exports :not-in))
  (set exports.not_contains (. exports :not-in))
  (set exports.between
    (fn [value low high]
      {:__tag :between :value ((. opts :wrap-expr) value) :low ((. opts :wrap-expr) low) :high ((. opts :wrap-expr) high)}))
  (set exports.slice (fn [value low high] (exports.between value low high)))
  (set (. exports :from-to)
       (fn [value start end]
         {:__tag :from-to :value ((. opts :wrap-expr) value) :start ((. opts :wrap-expr) start) :end ((. opts :wrap-expr) end)}))
  (set exports.from_to (. exports :from-to))
  (set (. exports :as-of)
       (fn [value point]
         {:__tag :as-of :value ((. opts :wrap-expr) value) :point ((. opts :wrap-expr) point)}))
  (set exports.as_of (. exports :as-of))
  (set exports.all_ (fn [value] {:__tag :all :expr ((. opts :wrap-expr) value)}))
  (set exports.any_ (fn [value] {:__tag :any :expr ((. opts :wrap-expr) value)}))
  (set (. exports :is-null) (fn [value] {:__tag :is-null :expr ((. opts :wrap-expr) value)}))
  (set (. exports :is-not-null) (fn [value] {:__tag :is-not-null :expr ((. opts :wrap-expr) value)}))
  (set exports.is_null (. exports :is-null))
  (set exports.is_not_null (. exports :is-not-null))
  (set exports.isnull (. exports :is-null))
  (set exports.notnull (. exports :is-not-null))
  (set exports.isnotnull (. exports :is-not-null))
  (set exports.not_ opts.not_)
  (set exports.negate opts.not_)
  (set exports.neg (fn [value] ((. opts :unary) :neg value)))
  (set exports.and_ opts.and_)
  (set exports.or_ opts.or_)
  (set exports.add opts.add)
  (set exports.sub opts.sub)
  (set exports.mul opts.mul)
  (set exports.div opts.div)
  (set exports.mod opts.mod)
  (set exports.exists opts.exists)
  (set exports.excluded opts.excluded)
  (set exports.tuple
    (fn [...]
      {:__tag :tuple
       :values (icollect [_ v (ipairs [...])] ((. opts :wrap-expr) v))}))
  (set exports.Tuple exports.tuple)
  (set exports.case_ opts.case_)
  (set exports.case
    (fn [base]
      (local c ((. opts :case_) [] nil base))
      (setmetatable c
        {:__index (fn [_ key]
                    (local method (. opts.case-methods key))
                    (if method method nil))})))
  (set exports.when_ (fn [cond value] {:when ((. opts :wrap-expr) cond) :then ((. opts :wrap-expr) value)}))
  (set exports.over
    (fn [fn-expr opts2]
      (local options (or opts2 {}))
      {:__tag :over
       :expr ((. opts :wrap-expr) fn-expr)
       :partition-by (icollect [_ v (ipairs (or options.partition-by []))] ((. opts :wrap-expr) v))
       :order-by ((. opts :copy-array) (or options.order-by []))
       :frame options.frame}))
  (set exports.preceding (fn [value] {:__tag :frame-edge :modifier "PRECEDING" :value value}))
  (set exports.following (fn [value] {:__tag :frame-edge :modifier "FOLLOWING" :value value}))
  (set exports.CURRENT_ROW opts.CURRENT_ROW)

  (set exports.call opts.call)
  (set exports.fn opts.call)
  (set (. exports :fn-distinct) opts.call-distinct)

  (set exports.Functions opts.function-catalog.Functions)
  (set exports.Analytics opts.function-catalog.Analytics)
  (set exports.Query opts.QueryFacade)

  (set exports.compile (fn [query options] (query:compile options)))
  (set (. exports :to-sql) (fn [query options] (query:to-sql options)))
  (set (. exports :to-sql-string) (fn [query options] (query:to-sql-string options)))

  (setmetatable exports {:__call (fn [_ ...]
                                   (opts.select ...))})

  exports)

{:install install}
