(local {: Layout : LayoutRoot} (require :layout))

(let [root (LayoutRoot)
      l2 (Layout {:name "l2"})
      l1 (Layout {:name "l1" :children [l2]})
      ]
  (assert (= l1.name "l1"))
  (assert (= (length l1.children) 1))
  (assert (= (. l1.children 1) l2))
  (l1:clear-children)
  (assert (= (length l1.children) 0))
  (l1:add-child l2)
  (assert (= (. l1.children 1) l2))
  (assert (= l1.layout-dirty false))
  (l1:set-position (glm.vec3:new 10 0 0))
  (assert (= l1.layout-dirty true))
  (assert (= l1.position.x 10))
  (assert (= l1.position.y 0))
  (l1:set-root root)
  (assert (. root.layout-dirt l1))
  (root:update)
  (assert (not (. root.layout-dirt l1)))
  (l1:drop)
  (l2:drop)
  )
